FROM python:3.10-slim-buster

# Inside Container
#Make a new folder inside container
WORKDIR /backend-flask

# Outside Container -> Instide Container
#This contains the libraries want to install to run app
COPY requirements.txt requirements.txt

#Inside Container 
#Install the python libraries used for the app
RUN pip3 install -r requirements.txt

#Outside Container -> Inside Container 
#Means everything in the current directory
#first period /backend-flask (Outside Container)
#second period /backend-lfash (inside container)
COPY . .

#Set Environment Variable (env vars)
#Container and will remain set when the container is running
ENV FLASK_ENV=development

EXPOSE ${PORT}

#cmd (command)
#python3 -m flask run --host=0.0.0.0 --port=4567
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=4567"]